version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"  # Пробрасываем порт для Frontend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5000:8000"  # Пробрасываем порт для Backend
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always
